CREATE TABLE [dbo].[FactOrderDetail] (
    [OrderKey]              INT            NOT NULL,
    [OrderDetailKey]        INT            NOT NULL,
    [ODSOrderID]            INT            NOT NULL,
    [ODSProductID]          INT            NOT NULL,
    [OrderDate]             DATETIME       NULL,
    [RequiredDate]          DATETIME       NULL,
    [ShippedDate]           DATETIME       NULL,
    [DaysToShip]            INT            NULL,
    [DaysOverdue]           INT            NULL,
    [UnitPrice]             MONEY          NULL,
    [UnitCost]              MONEY          NULL,
    [Quantity]              INT            NULL,
    [DiscountPercent]       DECIMAL (3, 2) NULL,
    [PerUnitDiscountAmount] MONEY          NULL,
    [LineTotal]             MONEY          NULL,
    [LineDiscountAmount]    MONEY          NULL,
    [SalesAmount]           MONEY          NULL,
    [OrderDiscountAmount]   MONEY          NULL,
    [OrderDiscountPercent]  DECIMAL (3, 2) NULL,
    [Freight]               MONEY          NULL,
    [Profit]                MONEY          NULL,
    [CustomerAddressKey]    INT            NULL,
    [DeliveryAddressKey]    INT            NULL,
    [ShipperKey]            INT            NULL,
    [SourceKey]             INT            NOT NULL,
    [CustomerKey]           INT            NOT NULL,
    [EmployeeKey]           INT            NULL,
    [ProductKey]            INT            NOT NULL,
    [ProductHistoryKey]     INT            NULL,
    [SupplierKey]           INT            NULL,
    [CategoryKey]           INT            NULL,
    [OrderDateKey]          INT            NULL,
    [RequiredDateKey]       INT            NULL,
    [ShippedDateKey]        INT            NULL,
    PRIMARY KEY CLUSTERED ([OrderKey] ASC, [OrderDetailKey] ASC),
    CONSTRAINT [FK_FactOrderDetail.CategoryKey] FOREIGN KEY ([CategoryKey]) REFERENCES [dbo].[DimCategory] ([CategoryKey]),
    CONSTRAINT [FK_FactOrderDetail.CustomerAddressKey] FOREIGN KEY ([CustomerAddressKey]) REFERENCES [dbo].[DimAddress] ([AddressKey]),
    CONSTRAINT [FK_FactOrderDetail.CustomerKey] FOREIGN KEY ([CustomerKey]) REFERENCES [dbo].[DimCustomer] ([CustomerKey]),
    CONSTRAINT [FK_FactOrderDetail.DeliveryAddressKey] FOREIGN KEY ([DeliveryAddressKey]) REFERENCES [dbo].[DimAddress] ([AddressKey]),
    CONSTRAINT [FK_FactOrderDetail.EmployeeKey] FOREIGN KEY ([EmployeeKey]) REFERENCES [dbo].[DimEmployees] ([EmployeeKey]),
    CONSTRAINT [FK_FactOrderDetail.OrderDate] FOREIGN KEY ([OrderDateKey]) REFERENCES [dbo].[DimDate] ([DateKey]),
    CONSTRAINT [FK_FactOrderDetail.ProductHistoryKey] FOREIGN KEY ([ProductHistoryKey]) REFERENCES [dbo].[DimProductHistory] ([ProductHistoryKey]),
    CONSTRAINT [FK_FactOrderDetail.ProductKey] FOREIGN KEY ([ProductKey]) REFERENCES [dbo].[DimProduct] ([ProductKey]),
    CONSTRAINT [FK_FactOrderDetail.RequiredDate] FOREIGN KEY ([RequiredDateKey]) REFERENCES [dbo].[DimDate] ([DateKey]),
    CONSTRAINT [FK_FactOrderDetail.ShippedDate] FOREIGN KEY ([ShippedDateKey]) REFERENCES [dbo].[DimDate] ([DateKey]),
    CONSTRAINT [FK_FactOrderDetail.ShipperKey] FOREIGN KEY ([ShipperKey]) REFERENCES [dbo].[DimShippers] ([ShipperKey]),
    CONSTRAINT [FK_FactOrderDetail.SourceKey] FOREIGN KEY ([SourceKey]) REFERENCES [dbo].[DimSource] ([SourceKey]),
    CONSTRAINT [FK_FactOrderDetail.SupplierKey] FOREIGN KEY ([SupplierKey]) REFERENCES [dbo].[DimSupplier] ([SupplierKey])
);

